# Generated by Django 5.2.17 on 2026-09-13 04:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=32, unique=True)),
                ('customer', models.CharField(max_length=128)),
                ('signed_date', models.DateField()),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=14)),
                ('note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='AccountingPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField()),
                ('month', models.PositiveSmallIntegerField()),
                ('is_closed', models.BooleanField(default=False)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['year', 'month'],
                'constraints': [models.UniqueConstraint(fields=('year', 'month'), name='uniq_period_year_month')],
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=32, unique=True)),
                ('invoice_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='revrec.contract')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='revrec.accountingperiod')),
            ],
            options={
                'ordering': ['period__year', 'period__month', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('received_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='revrec.contract')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='revrec.accountingperiod')),
            ],
            options={
                'ordering': ['period__year', 'period__month', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PerformanceObligation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('kind', models.CharField(choices=[('SUBSCRIPTION', '账号订阅'), ('IMPLEMENTATION', '一次性实施'), ('USAGE', '按量服务')], max_length=16)),
                ('ssp', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='独立售价')),
                ('service_start', models.DateField(blank=True, null=True)),
                ('service_end', models.DateField(blank=True, null=True)),
                ('estimated_units', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='预计总量')),
                ('unit_label', models.CharField(blank=True, default='次', max_length=16)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='obligations', to='revrec.contract')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('reference', models.CharField(max_length=64, verbose_name='验收单号')),
                ('accepted_date', models.DateField()),
                ('note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='revrec.accountingperiod')),
                ('obligation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to='revrec.performanceobligation')),
            ],
        ),
        migrations.CreateModel(
            name='AllocationVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_no', models.PositiveIntegerField()),
                ('reason', models.CharField(max_length=200)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=14)),
                ('total_ssp', models.DecimalField(decimal_places=2, max_digits=14)),
                ('residual_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocation_versions', to='revrec.contract')),
                ('residual_obligation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='revrec.performanceobligation')),
            ],
            options={
                'ordering': ['contract', 'version_no'],
            },
        ),
        migrations.CreateModel(
            name='AllocationLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ssp', models.DecimalField(decimal_places=2, max_digits=14)),
                ('ratio', models.DecimalField(decimal_places=10, max_digits=20)),
                ('allocated_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('is_residual_receiver', models.BooleanField(default=False)),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='revrec.allocationversion')),
                ('obligation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='revrec.performanceobligation')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='RecognitionEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('status', models.CharField(choices=[('PLANNED', '计划(未来期间)'), ('RECOGNIZED', '已确认'), ('PENDING', '待确认(缺证据)')], max_length=16)),
                ('source', models.CharField(choices=[('SUBSCRIPTION_SCHEDULE', '订阅直线分摊'), ('IMPLEMENTATION_ACCEPTANCE', '实施验收'), ('USAGE', '按量确认')], max_length=32)),
                ('note', models.CharField(blank=True, default='', max_length=200)),
                ('allocation_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='revrec.allocationline')),
                ('obligation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recognition_entries', to='revrec.performanceobligation')),
                ('period', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='revrec.accountingperiod')),
            ],
            options={
                'ordering': ['period__year', 'period__month', 'id'],
            },
        ),
        migrations.CreateModel(
            name='UsageRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=14)),
                ('note', models.CharField(blank=True, default='', max_length=200)),
                ('obligation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_records', to='revrec.performanceobligation')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='revrec.accountingperiod')),
            ],
            options={
                'ordering': ['period__year', 'period__month', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='allocationversion',
            constraint=models.UniqueConstraint(fields=('contract', 'version_no'), name='uniq_alloc_version'),
        ),
    ]
